export const styles = {
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "20px",
    marginBottom: "30px",
  },
  statCard: {
    backgroundColor: "#FFF",
    padding: "20px",
    borderRadius: "15px",
    border: "1px solid #E0E5F2",
  },
  statTitle: { color: "#A3AED0", fontSize: "0.85rem", fontWeight: "700" },
  statNumber: { fontSize: "1.8rem", color: "#2B3674", fontWeight: "800" },
  filterBar: {
    display: "flex",
    gap: "15px",
    marginBottom: "25px",
    flexWrap: "wrap",
  },
  input: {
    padding: "10px",
    borderRadius: "10px",
    border: "1px solid #E0E5F2",
    color: "#2B3674",
    outline: "none",
  },
  tableCard: {
    backgroundColor: "#FFF",
    padding: "20px",
    borderRadius: "15px",
    overflowX: "auto",
  },
  table: { width: "100%", borderCollapse: "collapse" },
  th: {
    textAlign: "left",
    padding: "12px",
    color: "#A3AED0",
    fontSize: "0.75rem",
    fontWeight: "bold",
  },
  td: { padding: "12px", borderBottom: "1px solid #F4F7FE", color: "#2B3674" },
  emptyRow: {
    textAlign: "center",
    padding: "40px",
    color: "#A3AED0",
    fontSize: "0.9rem",
    fontStyle: "italic",
  },
  actionsContainer: { display: "flex", gap: "5px", justifyContent: "flex-end" },
  btnFinalizar: {
    backgroundColor: "#4A148C",
    color: "#FFF",
    border: "none",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  btnCancelar: {
    backgroundColor: "#FFF",
    color: "#D32F2F",
    border: "1px solid #D32F2F",
    padding: "6px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  badgeSuccess: {
    backgroundColor: "#E8F5E9",
    color: "#2E7D32",
    padding: "5px 10px",
    borderRadius: "6px",
    fontSize: "0.7rem",
    fontWeight: "bold",
  },
  badgeCancel: {
    backgroundColor: "#FFEBEE",
    color: "#C62828",
    padding: "5px 10px",
    borderRadius: "6px",
    fontSize: "0.7rem",
    fontWeight: "bold",
  },
};
